### ISSUE TITLE
Thanks for making this crate

### ISSUE THREAD

**Issue by Boscop** [PierreLouisLetoquart/tavily-rs#2]
Thanks for making this crate, it's very useful!

Btw, are you doing RAG in Rust by any chance? 🙂

**Comment by PierreLouisLetoquart** [comment]
Hi bud, thanks and sorry for late answer.

Not yet but I'm planning to try to implement an agent using web queries with Tavilly and RAG in Rust. 

Tell me if there is any room to improvment for that simple crate and/or related ;)

**Comment by PierreLouisLetoquart** [comment]
Btw I've made some updates; I'll appriciate any feedbacks ;)
